name: UHC
main: net.samagames.uhc.UHC
version: 3.0

depend: [WorldEdit]
softdepend: [SamaGamesAPI]
load: startup

author: BlueSlime
website: http://samagames.net/

commands:
    uhc:
        description: Commandes UHC
        usage: /<command> <help>
    all:
        description: Chat
        usage: /all <Message>
