name: UHC
main: net.samagames.uhc.UHC
version: 3.0

depend: [SamaGamesAPI, WorldEdit]
load: startup

author: BlueSlime
website: http://samagames.net/

commands:
    uhc:
        description: Commandes UHC
        usage: /<command> <help>
        permission: UHC.op
        permission-message: Permission non accordée
    all:
        description: Chat
        usage: /all <Message>

permissions:
    UHC.op:
        description: Commandes OP UHC
        default: op