name: UHC
main: fr.blueslime.uhc.UHC
version: 1.0

depend: [MasterBundle]
load: startup

author: BlueSlime
website: http://blueslime.fr

commands:
    uhc:
        description: Commandes UHC
        usage: /<command> <help>
        permission: UHC.op
        permission-message: Permission non accordée
    all:
        description: Chat
        usage: /all <Message>
    inv:
        description: Voir l'inventaire d'un joueur
        usage: /inv <Joueur>
        permission: UHC.inv
        permission-message: Permission non accordée

permissions:
    UHC.op:
        description: Commandes OP UHC
        default: op
    UHC.inv:
        description: Commandes Inv UHC
        default: op