name: UHC
main: fr.blueslime.uhc.UHC
version: 1.0

depend: [WorldEdit]
softdepend: [SamaGamesAPI]
load: startup

author: BlueSlime
website: http://blueslime.fr

commands:
    uhc:
        description: Commandes UHC
        usage: /<command> <help>
    all:
        description: Chat
        usage: /all <Message>